// Code generated by ogen, DO NOT EDIT.
package api

type CreateTaskRes interface {
	createTaskRes()
}

type GetCurrentUserRes interface {
	getCurrentUserRes()
}

type GetTaskDependenciesRes interface {
	getTaskDependenciesRes()
}

type GetTaskRes interface {
	getTaskRes()
}

type GetTasksParentsRes interface {
	getTasksParentsRes()
}

type GetTasksParentsTreeRes interface {
	getTasksParentsTreeRes()
}

type GetTodoRes interface {
	getTodoRes()
}

type LinkTaskRes interface {
	linkTaskRes()
}

type SearchTaskRes interface {
	searchTaskRes()
}

type SetTaskDoneRes interface {
	setTaskDoneRes()
}

type SetTaskNotDoneRes interface {
	setTaskNotDoneRes()
}

type SignInRes interface {
	signInRes()
}

type UnlinkTaskRes interface {
	unlinkTaskRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}
