// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/uri"
)

// GetTaskParams is parameters of getTask operation.
type GetTaskParams struct {
	// The id of the task to retrieve.
	ID int
}

func unpackGetTaskParams(packed middleware.Parameters) (params GetTaskParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeGetTaskParams(args [1]string, r *http.Request) (params GetTaskParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// GetTaskDependenciesParams is parameters of getTaskDependencies operation.
type GetTaskDependenciesParams struct {
	// The id of the task to retrieve.
	ID int
}

func unpackGetTaskDependenciesParams(packed middleware.Parameters) (params GetTaskDependenciesParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeGetTaskDependenciesParams(args [1]string, r *http.Request) (params GetTaskDependenciesParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// GetTasksParentsParams is parameters of getTasksParents operation.
type GetTasksParentsParams struct {
	// The id of the task to retreive parents from.
	ID int
}

func unpackGetTasksParentsParams(packed middleware.Parameters) (params GetTasksParentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeGetTasksParentsParams(args [1]string, r *http.Request) (params GetTasksParentsParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// GetTasksParentsTreeParams is parameters of getTasksParentsTree operation.
type GetTasksParentsTreeParams struct {
	// The id of the task to retreive parents from.
	ID int
}

func unpackGetTasksParentsTreeParams(packed middleware.Parameters) (params GetTasksParentsTreeParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeGetTasksParentsTreeParams(args [1]string, r *http.Request) (params GetTasksParentsTreeParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// GetTodoParams is parameters of getTodo operation.
type GetTodoParams struct {
	// Task id which children would be iterated.
	ID int
}

func unpackGetTodoParams(packed middleware.Parameters) (params GetTodoParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeGetTodoParams(args [1]string, r *http.Request) (params GetTodoParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// LinkTaskParams is parameters of linkTask operation.
type LinkTaskParams struct {
	// Id of the task that should be dependant.
	ID int
}

func unpackLinkTaskParams(packed middleware.Parameters) (params LinkTaskParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeLinkTaskParams(args [1]string, r *http.Request) (params LinkTaskParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// SearchTaskParams is parameters of searchTask operation.
type SearchTaskParams struct {
	// Title to search.
	Title string
}

func unpackSearchTaskParams(packed middleware.Parameters) (params SearchTaskParams) {
	{
		key := middleware.ParameterKey{
			Name: "title",
			In:   "query",
		}
		params.Title = packed[key].(string)
	}
	return params
}

func decodeSearchTaskParams(args [0]string, r *http.Request) (params SearchTaskParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: title.
	{
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "title",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Title = c
				return nil
			}); err != nil {
				return params, errors.Wrap(err, "query: title: parse")
			}
		} else {
			return params, errors.Wrap(err, "query")
		}
	}
	return params, nil
}

// SetTaskDoneParams is parameters of setTaskDone operation.
type SetTaskDoneParams struct {
	// The id of the task to set done.
	ID int
}

func unpackSetTaskDoneParams(packed middleware.Parameters) (params SetTaskDoneParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeSetTaskDoneParams(args [1]string, r *http.Request) (params SetTaskDoneParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// SetTaskNotDoneParams is parameters of setTaskNotDone operation.
type SetTaskNotDoneParams struct {
	// The id of the task to set done.
	ID int
}

func unpackSetTaskNotDoneParams(packed middleware.Parameters) (params SetTaskNotDoneParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeSetTaskNotDoneParams(args [1]string, r *http.Request) (params SetTaskNotDoneParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}

// UnlinkTaskParams is parameters of unlinkTask operation.
type UnlinkTaskParams struct {
	// Id of task that should loose dependency.
	ID int
	// Id of task that should no longer be dependent from.
	DependsOnID int
}

func unpackUnlinkTaskParams(packed middleware.Parameters) (params UnlinkTaskParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "depends_on_id",
			In:   "path",
		}
		params.DependsOnID = packed[key].(int)
	}
	return params
}

func decodeUnlinkTaskParams(args [2]string, r *http.Request) (params UnlinkTaskParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	// Decode path: depends_on_id.
	{
		param := args[1]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "depends_on_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.DependsOnID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: depends_on_id: parse")
			}
		} else {
			return params, errors.New("path: depends_on_id: not specified")
		}
	}
	return params, nil
}

// UpdateTaskParams is parameters of updateTask operation.
type UpdateTaskParams struct {
	// The id of the task to update.
	ID int
}

func unpackUpdateTaskParams(packed middleware.Parameters) (params UpdateTaskParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeUpdateTaskParams(args [1]string, r *http.Request) (params UpdateTaskParams, _ error) {
	// Decode path: id.
	{
		param := args[0]
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return params, errors.Wrap(err, "path: id: parse")
			}
		} else {
			return params, errors.New("path: id: not specified")
		}
	}
	return params, nil
}
