// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements createTask operation.
//
// Create Task.
//
// POST /tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req OptNewTaskForm) (r CreateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentUser implements getCurrentUser operation.
//
// Get current user info.
//
// GET /auth/user
func (UnimplementedHandler) GetCurrentUser(ctx context.Context) (r GetCurrentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTask implements getTask operation.
//
// Get Task.
//
// GET /tasks/{id}
func (UnimplementedHandler) GetTask(ctx context.Context, params GetTaskParams) (r GetTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskDependencies implements getTaskDependencies operation.
//
// Get dependencies.
//
// GET /tasks/{id}/dependencies
func (UnimplementedHandler) GetTaskDependencies(ctx context.Context, params GetTaskDependenciesParams) (r GetTaskDependenciesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTasksParents implements getTasksParents operation.
//
// Get parent tasks.
//
// GET /tasks/{id}/parents
func (UnimplementedHandler) GetTasksParents(ctx context.Context, params GetTasksParentsParams) (r GetTasksParentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTasksParentsTree implements getTasksParentsTree operation.
//
// Get parent tasks tree.
//
// GET /tasks/{id}/parents-tree
func (UnimplementedHandler) GetTasksParentsTree(ctx context.Context, params GetTasksParentsTreeParams) (r GetTasksParentsTreeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTodo implements getTodo operation.
//
// Get next task to do.
//
// GET /tasks/{id}/todo
func (UnimplementedHandler) GetTodo(ctx context.Context, params GetTodoParams) (r GetTodoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinkTask implements linkTask operation.
//
// Make task with id dependant of another one.
//
// POST /tasks/{id}/dependencies
func (UnimplementedHandler) LinkTask(ctx context.Context, req OptDependencyForm, params LinkTaskParams) (r LinkTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LogOut implements logOut operation.
//
// Log out.
//
// DELETE /auth/session
func (UnimplementedHandler) LogOut(ctx context.Context) (r LogOutOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchTask implements searchTask operation.
//
// Search task.
//
// GET /tasks/search
func (UnimplementedHandler) SearchTask(ctx context.Context, params SearchTaskParams) (r SearchTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetTaskDone implements setTaskDone operation.
//
// Set Task Done.
//
// PUT /tasks/{id}/done
func (UnimplementedHandler) SetTaskDone(ctx context.Context, params SetTaskDoneParams) (r SetTaskDoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetTaskNotDone implements setTaskNotDone operation.
//
// Set Task not done.
//
// DELETE /tasks/{id}/done
func (UnimplementedHandler) SetTaskNotDone(ctx context.Context, params SetTaskNotDoneParams) (r SetTaskNotDoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SignIn implements signIn operation.
//
// POST /auth/session
func (UnimplementedHandler) SignIn(ctx context.Context, req OptSignInForm) (r SignInRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SignUp implements signUp operation.
//
// Sign up user.
//
// POST /auth/user
func (UnimplementedHandler) SignUp(ctx context.Context, req OptSignUpForm) (r SignUpOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UnlinkTask implements unlinkTask operation.
//
// Unlink task.
//
// DELETE /tasks/{id}/dependencies/{depends_on_id}
func (UnimplementedHandler) UnlinkTask(ctx context.Context, params UnlinkTaskParams) (r UnlinkTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// Update Task.
//
// PUT /tasks/{id}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req OptTaskUpdateForm, params UpdateTaskParams) (r UpdateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}
